"""
Frontend YeetCode challenge seed data.
Each challenge has starter code, solution code, and DOM-based test assertions.
"""

import json

FRONTEND_CHALLENGES = [
    # ═══════════════════════════════════════════════════════════════════════════
    # BUILD THIS UI
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "challenge_id": "login-form",
        "title": "Build a Login Form",
        "category": "forms",
        "type": "build_ui",
        "difficulty": "easy",
        "description": "Create a login form with an email input, a password input, and a submit button. The button should have a blue background (#3b82f6), white text, and rounded corners (at least 4px border-radius).",
        "starter_html": '<form class="login-form">\n  <!-- Add your inputs and button here -->\n</form>',
        "starter_css": ".login-form {\n  max-width: 400px;\n  margin: 2rem auto;\n  padding: 2rem;\n  font-family: sans-serif;\n}\n\n/* Style your inputs and button below */\n",
        "starter_js": "",
        "solution_html": '<form class="login-form">\n  <input type="email" placeholder="Email" />\n  <input type="password" placeholder="Password" />\n  <button type="submit">Log In</button>\n</form>',
        "solution_css": ".login-form {\n  max-width: 400px;\n  margin: 2rem auto;\n  padding: 2rem;\n  font-family: sans-serif;\n}\n.login-form input {\n  display: block;\n  width: 100%;\n  margin-bottom: 1rem;\n  padding: 0.5rem;\n  border: 1px solid #ccc;\n  border-radius: 4px;\n  box-sizing: border-box;\n}\n.login-form button {\n  background: #3b82f6;\n  color: white;\n  border: none;\n  padding: 0.75rem 1.5rem;\n  border-radius: 8px;\n  cursor: pointer;\n  font-size: 1rem;\n}",
        "solution_js": "",
        "test_cases": json.dumps([
            {"type": "element_exists", "selector": "input[type='email']", "description": "Has an email input"},
            {"type": "element_exists", "selector": "input[type='password']", "description": "Has a password input"},
            {"type": "element_exists", "selector": "button[type='submit'], button", "description": "Has a submit button"},
            {"type": "has_style", "selector": "button", "property": "backgroundColor", "expected": "rgb(59, 130, 246)", "description": "Button has blue background (#3b82f6)"},
            {"type": "has_style_min", "selector": "button", "property": "borderRadius", "min_px": 4, "description": "Button has rounded corners (>= 4px)"},
            {"type": "has_style", "selector": "button", "property": "color", "expected": "rgb(255, 255, 255)", "description": "Button has white text"},
        ]),
        "hints": json.dumps(["Use type='email' for the email field", "border-radius controls corner rounding", "Set background: #3b82f6 and color: white on the button"]),
    },
    {
        "challenge_id": "nav-bar",
        "title": "Build a Navigation Bar",
        "category": "layout",
        "type": "build_ui",
        "difficulty": "easy",
        "description": "Create a horizontal navigation bar with:\n- A logo text that says 'YeetCode' on the left\n- Three navigation links: Home, About, Contact\n- Links should be laid out horizontally (use flexbox)\n- The navbar should have a dark background (#1a1a2e) and white text",
        "starter_html": '<nav class="navbar">\n  <!-- Add logo and links here -->\n</nav>',
        "starter_css": "* { margin: 0; padding: 0; box-sizing: border-box; }\n\n.navbar {\n  /* Style the navbar */\n}\n",
        "starter_js": "",
        "solution_html": '<nav class="navbar">\n  <span class="logo">YeetCode</span>\n  <ul class="nav-links">\n    <li><a href="#">Home</a></li>\n    <li><a href="#">About</a></li>\n    <li><a href="#">Contact</a></li>\n  </ul>\n</nav>',
        "solution_css": "* { margin: 0; padding: 0; box-sizing: border-box; }\n.navbar {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding: 1rem 2rem;\n  background: #1a1a2e;\n  color: white;\n}\n.logo { font-weight: bold; font-size: 1.25rem; }\n.nav-links { display: flex; list-style: none; gap: 1.5rem; }\n.nav-links a { color: white; text-decoration: none; }",
        "solution_js": "",
        "test_cases": json.dumps([
            {"type": "has_text", "selector": ".logo, nav span, nav strong, nav b", "expected": "YeetCode", "description": "Has logo text 'YeetCode'"},
            {"type": "element_count", "selector": "a", "expected": 3, "description": "Has 3 navigation links"},
            {"type": "has_style", "selector": ".navbar, nav", "property": "display", "expected": "flex", "description": "Navbar uses flexbox"},
            {"type": "has_style", "selector": ".navbar, nav", "property": "backgroundColor", "expected": "rgb(26, 26, 46)", "description": "Navbar has dark background (#1a1a2e)"},
        ]),
        "hints": json.dumps(["Use display: flex on the navbar to lay items out horizontally", "Use justify-content: space-between to push logo left and links right"]),
    },
    {
        "challenge_id": "pricing-cards",
        "title": "Build Pricing Cards",
        "category": "layout",
        "type": "build_ui",
        "difficulty": "medium",
        "description": "Create a pricing section with 3 cards side by side:\n- Each card should have a plan name (Basic, Pro, Enterprise), a price, and a feature list\n- Use flexbox or grid to lay them out horizontally\n- The middle card (Pro) should be visually highlighted with a different background color\n- Cards should have a border and some padding",
        "starter_html": '<div class="pricing">\n  <!-- Add 3 pricing cards here -->\n</div>',
        "starter_css": "* { margin: 0; padding: 0; box-sizing: border-box; }\nbody { font-family: sans-serif; padding: 2rem; background: #f5f5f5; }\n\n.pricing {\n  /* Layout your cards here */\n}\n",
        "starter_js": "",
        "solution_html": '<div class="pricing">\n  <div class="card">\n    <h2>Basic</h2>\n    <p class="price">$9/mo</p>\n    <ul><li>5 Projects</li><li>1GB Storage</li></ul>\n  </div>\n  <div class="card featured">\n    <h2>Pro</h2>\n    <p class="price">$29/mo</p>\n    <ul><li>Unlimited Projects</li><li>10GB Storage</li></ul>\n  </div>\n  <div class="card">\n    <h2>Enterprise</h2>\n    <p class="price">$99/mo</p>\n    <ul><li>Unlimited Everything</li><li>Priority Support</li></ul>\n  </div>\n</div>',
        "solution_css": "* { margin:0; padding:0; box-sizing:border-box; }\nbody { font-family:sans-serif; padding:2rem; background:#f5f5f5; }\n.pricing { display:flex; gap:1.5rem; justify-content:center; }\n.card { background:white; border:2px solid #ddd; border-radius:12px; padding:2rem; text-align:center; flex:1; max-width:300px; }\n.card.featured { background:#eef2ff; border-color:#3b82f6; }\n.price { font-size:2rem; font-weight:bold; margin:1rem 0; }\nul { list-style:none; text-align:left; padding:0; }\nli { padding:0.5rem 0; border-bottom:1px solid #eee; }",
        "solution_js": "",
        "test_cases": json.dumps([
            {"type": "element_count", "selector": ".card, .pricing > div", "expected": 3, "description": "Has 3 pricing cards"},
            {"type": "has_text", "selector": ".pricing", "expected": "Basic", "description": "Has 'Basic' plan"},
            {"type": "has_text", "selector": ".pricing", "expected": "Pro", "description": "Has 'Pro' plan"},
            {"type": "has_text", "selector": ".pricing", "expected": "Enterprise", "description": "Has 'Enterprise' plan"},
            {"type": "has_style", "selector": ".pricing", "property": "display", "expected": "flex", "description": "Cards use flexbox layout"},
            {"type": "has_class", "selector": ".featured, .card.featured, .card.highlight, .card:nth-child(2)", "description": "Middle card is highlighted"},
        ]),
        "hints": json.dumps(["Use display: flex with gap on the container", "Add a special class like 'featured' to the Pro card and give it a different background"]),
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # CSS-ONLY CHALLENGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "challenge_id": "center-a-div",
        "title": "Center a Div",
        "category": "layout",
        "type": "css_only",
        "difficulty": "easy",
        "description": "Center the red box both horizontally and vertically within its container. The HTML is fixed — you can only write CSS.",
        "starter_html": '<div class="container">\n  <div class="box"></div>\n</div>',
        "starter_css": ".container {\n  width: 300px;\n  height: 300px;\n  border: 2px dashed #999;\n  /* Center the box inside this container */\n}\n\n.box {\n  width: 80px;\n  height: 80px;\n  background: #ef4444;\n}",
        "starter_js": "",
        "solution_html": '<div class="container">\n  <div class="box"></div>\n</div>',
        "solution_css": ".container {\n  width: 300px;\n  height: 300px;\n  border: 2px dashed #999;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n.box {\n  width: 80px;\n  height: 80px;\n  background: #ef4444;\n}",
        "solution_js": "",
        "test_cases": json.dumps([
            {"type": "has_style", "selector": ".container", "property": "display", "expected": "flex", "description": "Container uses flexbox"},
            {"type": "has_style", "selector": ".container", "property": "alignItems", "expected": "center", "description": "Items are vertically centered"},
            {"type": "has_style", "selector": ".container", "property": "justifyContent", "expected": "center", "description": "Items are horizontally centered"},
            {"type": "layout_check", "selector": ".box", "parent": ".container", "check": "centered", "tolerance": 5, "description": "Box is visually centered in container"},
        ]),
        "hints": json.dumps(["Flexbox can center in both directions", "align-items centers vertically, justify-content centers horizontally"]),
    },
    {
        "challenge_id": "hover-card",
        "title": "Hover Card Effect",
        "category": "styling",
        "type": "css_only",
        "difficulty": "easy",
        "description": "Add a hover effect to the card:\n- On hover, the card should move up by 4px (transform: translateY)\n- Add a smooth transition (0.2s or more)\n- On hover, add a box shadow\n\nThe HTML is fixed — only write CSS.",
        "starter_html": '<div class="card">\n  <h2>Premium Plan</h2>\n  <p>Everything you need to succeed.</p>\n</div>',
        "starter_css": "body { display:flex; justify-content:center; padding:4rem; background:#f0f0f0; font-family:sans-serif; }\n\n.card {\n  background: white;\n  padding: 2rem;\n  border-radius: 12px;\n  border: 1px solid #ddd;\n  width: 280px;\n  /* Add transition and hover styles */\n}",
        "starter_js": "",
        "solution_html": '<div class="card">\n  <h2>Premium Plan</h2>\n  <p>Everything you need to succeed.</p>\n</div>',
        "solution_css": "body { display:flex; justify-content:center; padding:4rem; background:#f0f0f0; font-family:sans-serif; }\n.card {\n  background:white; padding:2rem; border-radius:12px; border:1px solid #ddd; width:280px;\n  transition: transform 0.2s, box-shadow 0.2s;\n}\n.card:hover {\n  transform: translateY(-4px);\n  box-shadow: 0 8px 24px rgba(0,0,0,0.12);\n}",
        "solution_js": "",
        "test_cases": json.dumps([
            {"type": "has_style_nonzero", "selector": ".card", "property": "transitionDuration", "description": "Card has a CSS transition"},
            {"type": "element_exists", "selector": ".card", "description": "Card element exists"},
        ]),
        "hints": json.dumps(["Use transition: transform 0.2s on the card", "Use .card:hover { transform: translateY(-4px); } for the lift effect"]),
    },
    {
        "challenge_id": "responsive-grid",
        "title": "Responsive Grid Layout",
        "category": "layout",
        "type": "css_only",
        "difficulty": "medium",
        "description": "Make the grid display:\n- 3 columns on screens wider than 600px\n- 1 column on screens 600px and below\n- Use CSS Grid\n- Add a gap of 1rem between items\n\nThe HTML is fixed — only write CSS.",
        "starter_html": '<div class="grid">\n  <div class="item">1</div>\n  <div class="item">2</div>\n  <div class="item">3</div>\n  <div class="item">4</div>\n  <div class="item">5</div>\n  <div class="item">6</div>\n</div>',
        "starter_css": "body { padding: 1rem; font-family: sans-serif; }\n\n.grid {\n  /* Add your grid styles */\n}\n\n.item {\n  background: #3b82f6;\n  color: white;\n  padding: 2rem;\n  text-align: center;\n  font-weight: bold;\n  font-size: 1.5rem;\n  border-radius: 8px;\n}",
        "starter_js": "",
        "solution_html": '<div class="grid">\n  <div class="item">1</div>\n  <div class="item">2</div>\n  <div class="item">3</div>\n  <div class="item">4</div>\n  <div class="item">5</div>\n  <div class="item">6</div>\n</div>',
        "solution_css": "body { padding:1rem; font-family:sans-serif; }\n.grid { display:grid; grid-template-columns:repeat(3,1fr); gap:1rem; }\n.item { background:#3b82f6; color:white; padding:2rem; text-align:center; font-weight:bold; font-size:1.5rem; border-radius:8px; }\n@media (max-width:600px) { .grid { grid-template-columns:1fr; } }",
        "solution_js": "",
        "test_cases": json.dumps([
            {"type": "has_style", "selector": ".grid", "property": "display", "expected": "grid", "description": "Uses CSS Grid"},
            {"type": "has_style_contains", "selector": ".grid", "property": "gridTemplateColumns", "expected": "1fr", "description": "Grid has fractional columns defined"},
            {"type": "has_style_nonzero", "selector": ".grid", "property": "gap", "description": "Grid has gap between items"},
            {"type": "element_count", "selector": ".item", "expected": 6, "description": "Has 6 grid items"},
        ]),
        "hints": json.dumps(["Use display: grid and grid-template-columns: repeat(3, 1fr)", "Use @media (max-width: 600px) to change to 1 column"]),
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # FIX THE BUG
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "challenge_id": "broken-flexbox",
        "title": "Fix the Broken Flexbox",
        "category": "debugging",
        "type": "fix_bug",
        "difficulty": "easy",
        "description": "The three boxes should be centered horizontally inside the container, but they're not. Find and fix the CSS bug.\n\nHint: check the flexbox properties on the container.",
        "starter_html": '<div class="container">\n  <div class="box">A</div>\n  <div class="box">B</div>\n  <div class="box">C</div>\n</div>',
        "starter_css": "body { padding: 2rem; font-family: sans-serif; }\n\n.container {\n  display: block;\n  justify-content: center;\n  gap: 1rem;\n  padding: 2rem;\n  background: #f0f0f0;\n  border-radius: 8px;\n}\n\n.box {\n  width: 80px;\n  height: 80px;\n  background: #3b82f6;\n  color: white;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  font-weight: bold;\n  border-radius: 4px;\n}",
        "starter_js": "",
        "solution_html": '<div class="container">\n  <div class="box">A</div>\n  <div class="box">B</div>\n  <div class="box">C</div>\n</div>',
        "solution_css": "body { padding: 2rem; font-family: sans-serif; }\n.container {\n  display: flex;\n  justify-content: center;\n  gap: 1rem;\n  padding: 2rem;\n  background: #f0f0f0;\n  border-radius: 8px;\n}\n.box {\n  width: 80px;\n  height: 80px;\n  background: #3b82f6;\n  color: white;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  font-weight: bold;\n  border-radius: 4px;\n}",
        "solution_js": "",
        "test_cases": json.dumps([
            {"type": "has_style", "selector": ".container", "property": "display", "expected": "flex", "description": "Container uses display: flex"},
            {"type": "has_style", "selector": ".container", "property": "justifyContent", "expected": "center", "description": "Items are centered horizontally"},
            {"type": "element_count", "selector": ".box", "expected": 3, "description": "All 3 boxes are present"},
        ]),
        "hints": json.dumps(["The container has display: block but uses justify-content, which only works with flexbox", "Change display: block to display: flex"]),
    },
    {
        "challenge_id": "broken-toggle",
        "title": "Fix the Toggle Button",
        "category": "debugging",
        "type": "fix_bug",
        "difficulty": "easy",
        "description": "The button should toggle the text between 'ON' and 'OFF' when clicked, but it doesn't work. Find and fix the JavaScript bug.",
        "starter_html": '<button id="toggle-btn">OFF</button>',
        "starter_css": "body { display:flex; justify-content:center; padding:4rem; font-family:sans-serif; }\n#toggle-btn {\n  padding: 1rem 2rem;\n  font-size: 1.5rem;\n  font-weight: bold;\n  border: 2px solid #333;\n  border-radius: 8px;\n  cursor: pointer;\n  background: #ef4444;\n  color: white;\n}",
        "starter_js": 'const btn = document.getElementById("toggle-btn");\n\nbtn.addEventlistener("click", function() {\n  if (btn.textContent === "OFF") {\n    btn.textContent = "ON";\n    btn.style.background = "#22c55e";\n  } else {\n    btn.textContent = "OFF";\n    btn.style.background = "#ef4444";\n  }\n});',
        "solution_html": '<button id="toggle-btn">OFF</button>',
        "solution_css": "body { display:flex; justify-content:center; padding:4rem; font-family:sans-serif; }\n#toggle-btn { padding:1rem 2rem; font-size:1.5rem; font-weight:bold; border:2px solid #333; border-radius:8px; cursor:pointer; background:#ef4444; color:white; }",
        "solution_js": 'const btn = document.getElementById("toggle-btn");\n\nbtn.addEventListener("click", function() {\n  if (btn.textContent === "OFF") {\n    btn.textContent = "ON";\n    btn.style.background = "#22c55e";\n  } else {\n    btn.textContent = "OFF";\n    btn.style.background = "#ef4444";\n  }\n});',
        "solution_js": 'const btn = document.getElementById("toggle-btn");\nbtn.addEventListener("click", function() {\n  if (btn.textContent === "OFF") {\n    btn.textContent = "ON";\n    btn.style.background = "#22c55e";\n  } else {\n    btn.textContent = "OFF";\n    btn.style.background = "#ef4444";\n  }\n});',
        "test_cases": json.dumps([
            {"type": "element_exists", "selector": "#toggle-btn", "description": "Toggle button exists"},
            {"type": "event_test", "selector": "#toggle-btn", "event": "click", "then_check": {"type": "has_text", "selector": "#toggle-btn", "expected": "ON"}, "description": "Clicking toggles text to 'ON'"},
            {"type": "event_test", "selector": "#toggle-btn", "event": "click", "click_count": 2, "then_check": {"type": "has_text", "selector": "#toggle-btn", "expected": "OFF"}, "description": "Clicking twice toggles back to 'OFF'"},
        ]),
        "hints": json.dumps(["Look carefully at the method name — JavaScript is case-sensitive", "It should be addEventListener, not addEventlistener"]),
    },
    {
        "challenge_id": "broken-form-validation",
        "title": "Fix the Form Validation",
        "category": "debugging",
        "type": "fix_bug",
        "difficulty": "medium",
        "description": "This form should show an error message when the email field is empty and the user clicks Submit. The validation logic exists but the error message never appears. Find and fix the bug.",
        "starter_html": '<form id="signup-form">\n  <input type="email" id="email" placeholder="Email" />\n  <span id="error" class="error"></span>\n  <button type="submit">Submit</button>\n</form>',
        "starter_css": "body { display:flex; justify-content:center; padding:4rem; font-family:sans-serif; }\n#signup-form { width:300px; }\ninput { display:block; width:100%; padding:0.5rem; margin-bottom:0.5rem; border:2px solid #ccc; border-radius:4px; box-sizing:border-box; }\n.error { color:red; font-size:0.875rem; display:block; min-height:1.25rem; }\nbutton { background:#3b82f6; color:white; border:none; padding:0.75rem; width:100%; border-radius:4px; cursor:pointer; margin-top:0.5rem; }",
        "starter_js": 'const form = document.getElementById("signup-form");\nconst email = document.getElementById("email");\nconst error = document.getElementById("error");\n\nform.addEventListener("submit", function(e) {\n  e.preventDefault();\n  if (email.value === "") {\n    error.innerText = "Email is required";\n  } else {\n    error.innertext = "";\n    alert("Submitted!");\n  }\n});',
        "solution_html": '<form id="signup-form">\n  <input type="email" id="email" placeholder="Email" />\n  <span id="error" class="error"></span>\n  <button type="submit">Submit</button>\n</form>',
        "solution_css": "body { display:flex; justify-content:center; padding:4rem; font-family:sans-serif; }\n#signup-form { width:300px; }\ninput { display:block; width:100%; padding:0.5rem; margin-bottom:0.5rem; border:2px solid #ccc; border-radius:4px; box-sizing:border-box; }\n.error { color:red; font-size:0.875rem; display:block; min-height:1.25rem; }\nbutton { background:#3b82f6; color:white; border:none; padding:0.75rem; width:100%; border-radius:4px; cursor:pointer; margin-top:0.5rem; }",
        "solution_js": 'const form = document.getElementById("signup-form");\nconst email = document.getElementById("email");\nconst error = document.getElementById("error");\n\nform.addEventListener("submit", function(e) {\n  e.preventDefault();\n  if (email.value === "") {\n    error.innerText = "Email is required";\n  } else {\n    error.innerText = "";\n    alert("Submitted!");\n  }\n});',
        "test_cases": json.dumps([
            {"type": "element_exists", "selector": "#signup-form", "description": "Form exists"},
            {"type": "event_test", "selector": "#signup-form", "event": "submit", "then_check": {"type": "has_text", "selector": "#error", "expected": "Email is required"}, "description": "Empty submit shows error message"},
        ]),
        "hints": json.dumps(["The error appears on empty submit but doesn't clear on valid submit", "Look at the else branch — is the property name correct? (innerText vs innertext)"]),
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DOM MANIPULATION
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "challenge_id": "toggle-dark-mode",
        "title": "Toggle Dark Mode",
        "category": "interactivity",
        "type": "dom_manipulation",
        "difficulty": "easy",
        "description": "Write JavaScript to make the 'Toggle Theme' button switch between light and dark mode.\n\nWhen clicked, toggle the class 'dark' on the <body> element. The CSS for dark mode is already written — you just need the JS.",
        "starter_html": '<div class="page">\n  <h1>Hello World</h1>\n  <p>Click the button to toggle dark mode.</p>\n  <button id="theme-btn">Toggle Theme</button>\n</div>',
        "starter_css": "body {\n  font-family: sans-serif;\n  padding: 2rem;\n  transition: background 0.3s, color 0.3s;\n}\nbody.dark {\n  background: #1a1a2e;\n  color: #e0e0e0;\n}\n#theme-btn {\n  padding: 0.75rem 1.5rem;\n  border: 2px solid #333;\n  border-radius: 8px;\n  cursor: pointer;\n  font-weight: bold;\n  margin-top: 1rem;\n}",
        "starter_js": "// Write your JavaScript here\n// Toggle the 'dark' class on document.body when the button is clicked\n",
        "solution_html": '<div class="page">\n  <h1>Hello World</h1>\n  <p>Click the button to toggle dark mode.</p>\n  <button id="theme-btn">Toggle Theme</button>\n</div>',
        "solution_css": "body { font-family:sans-serif; padding:2rem; transition:background 0.3s, color 0.3s; }\nbody.dark { background:#1a1a2e; color:#e0e0e0; }\n#theme-btn { padding:0.75rem 1.5rem; border:2px solid #333; border-radius:8px; cursor:pointer; font-weight:bold; margin-top:1rem; }",
        "solution_js": 'document.getElementById("theme-btn").addEventListener("click", function() {\n  document.body.classList.toggle("dark");\n});',
        "test_cases": json.dumps([
            {"type": "element_exists", "selector": "#theme-btn", "description": "Theme button exists"},
            {"type": "event_test", "selector": "#theme-btn", "event": "click", "then_check": {"type": "has_class", "selector": "body", "className": "dark"}, "description": "Clicking button adds 'dark' class to body"},
            {"type": "event_test", "selector": "#theme-btn", "event": "click", "click_count": 2, "then_check": {"type": "not_has_class", "selector": "body", "className": "dark"}, "description": "Clicking twice removes 'dark' class"},
        ]),
        "hints": json.dumps(["Use document.body.classList.toggle('dark')", "addEventListener('click', ...) to listen for the click"]),
    },
    {
        "challenge_id": "todo-list",
        "title": "Build a Todo List",
        "category": "interactivity",
        "type": "dom_manipulation",
        "difficulty": "medium",
        "description": "Make the todo list work:\n1. Type in the input and click 'Add' (or press Enter) to add a new todo item to the list\n2. Each todo should appear as an <li> inside the <ul>\n3. Clear the input after adding\n\nThe HTML structure is given — write the JavaScript.",
        "starter_html": '<div class="todo-app">\n  <h2>Todo List</h2>\n  <div class="input-row">\n    <input type="text" id="todo-input" placeholder="Add a task..." />\n    <button id="add-btn">Add</button>\n  </div>\n  <ul id="todo-list"></ul>\n</div>',
        "starter_css": "body { display:flex; justify-content:center; padding:2rem; font-family:sans-serif; }\n.todo-app { width:350px; }\n.input-row { display:flex; gap:0.5rem; margin-bottom:1rem; }\n#todo-input { flex:1; padding:0.5rem; border:2px solid #ccc; border-radius:4px; }\n#add-btn { background:#3b82f6; color:white; border:none; padding:0.5rem 1rem; border-radius:4px; cursor:pointer; font-weight:bold; }\n#todo-list { list-style:none; padding:0; }\n#todo-list li { padding:0.75rem; border-bottom:1px solid #eee; }",
        "starter_js": "// Write your JavaScript here\n// 1. Get references to the input, button, and list\n// 2. When 'Add' is clicked, create an <li> with the input text and append it to the list\n// 3. Clear the input after adding\n",
        "solution_html": '<div class="todo-app">\n  <h2>Todo List</h2>\n  <div class="input-row">\n    <input type="text" id="todo-input" placeholder="Add a task..." />\n    <button id="add-btn">Add</button>\n  </div>\n  <ul id="todo-list"></ul>\n</div>',
        "solution_css": "body { display:flex; justify-content:center; padding:2rem; font-family:sans-serif; }\n.todo-app { width:350px; }\n.input-row { display:flex; gap:0.5rem; margin-bottom:1rem; }\n#todo-input { flex:1; padding:0.5rem; border:2px solid #ccc; border-radius:4px; }\n#add-btn { background:#3b82f6; color:white; border:none; padding:0.5rem 1rem; border-radius:4px; cursor:pointer; font-weight:bold; }\n#todo-list { list-style:none; padding:0; }\n#todo-list li { padding:0.75rem; border-bottom:1px solid #eee; }",
        "solution_js": 'const input = document.getElementById("todo-input");\nconst btn = document.getElementById("add-btn");\nconst list = document.getElementById("todo-list");\n\nfunction addTodo() {\n  const text = input.value.trim();\n  if (!text) return;\n  const li = document.createElement("li");\n  li.textContent = text;\n  list.appendChild(li);\n  input.value = "";\n}\n\nbtn.addEventListener("click", addTodo);\ninput.addEventListener("keydown", function(e) {\n  if (e.key === "Enter") addTodo();\n});',
        "test_cases": json.dumps([
            {"type": "element_exists", "selector": "#todo-input", "description": "Input field exists"},
            {"type": "element_exists", "selector": "#add-btn", "description": "Add button exists"},
            {"type": "element_exists", "selector": "#todo-list", "description": "Todo list exists"},
            {"type": "input_then_click", "input_selector": "#todo-input", "input_value": "Buy milk", "click_selector": "#add-btn", "then_check": {"type": "has_text", "selector": "#todo-list", "expected": "Buy milk"}, "description": "Typing and clicking Add creates a todo item"},
            {"type": "input_then_click", "input_selector": "#todo-input", "input_value": "Walk dog", "click_selector": "#add-btn", "then_check": {"type": "element_count", "selector": "#todo-list li", "expected": 2}, "description": "Adding a second todo creates 2 list items"},
        ]),
        "hints": json.dumps(["Use document.createElement('li') to create list items", "Use list.appendChild(li) to add them to the <ul>", "Clear input with input.value = '' after adding"]),
    },
    {
        "challenge_id": "live-search",
        "title": "Live Search Filter",
        "category": "interactivity",
        "type": "dom_manipulation",
        "difficulty": "medium",
        "description": "Write JavaScript to filter the list of fruits as the user types in the search box.\n- Hide list items that don't match the search text (case-insensitive)\n- Show all items when the search box is empty\n- Use display: none to hide non-matching items",
        "starter_html": '<div class="search-app">\n  <input type="text" id="search" placeholder="Search fruits..." />\n  <ul id="fruit-list">\n    <li>Apple</li>\n    <li>Banana</li>\n    <li>Cherry</li>\n    <li>Date</li>\n    <li>Elderberry</li>\n    <li>Fig</li>\n    <li>Grape</li>\n  </ul>\n</div>',
        "starter_css": "body { display:flex; justify-content:center; padding:2rem; font-family:sans-serif; }\n.search-app { width:300px; }\n#search { width:100%; padding:0.75rem; border:2px solid #ccc; border-radius:8px; margin-bottom:1rem; box-sizing:border-box; font-size:1rem; }\n#fruit-list { list-style:none; padding:0; }\n#fruit-list li { padding:0.5rem 0; border-bottom:1px solid #eee; }",
        "starter_js": "// Write your JavaScript here\n// Filter the fruit list based on the search input\n",
        "solution_html": '<div class="search-app">\n  <input type="text" id="search" placeholder="Search fruits..." />\n  <ul id="fruit-list">\n    <li>Apple</li>\n    <li>Banana</li>\n    <li>Cherry</li>\n    <li>Date</li>\n    <li>Elderberry</li>\n    <li>Fig</li>\n    <li>Grape</li>\n  </ul>\n</div>',
        "solution_css": "body { display:flex; justify-content:center; padding:2rem; font-family:sans-serif; }\n.search-app { width:300px; }\n#search { width:100%; padding:0.75rem; border:2px solid #ccc; border-radius:8px; margin-bottom:1rem; box-sizing:border-box; font-size:1rem; }\n#fruit-list { list-style:none; padding:0; }\n#fruit-list li { padding:0.5rem 0; border-bottom:1px solid #eee; }",
        "solution_js": 'const search = document.getElementById("search");\nconst items = document.querySelectorAll("#fruit-list li");\n\nsearch.addEventListener("input", function() {\n  const query = search.value.toLowerCase();\n  items.forEach(function(item) {\n    if (item.textContent.toLowerCase().includes(query)) {\n      item.style.display = "";\n    } else {\n      item.style.display = "none";\n    }\n  });\n});',
        "test_cases": json.dumps([
            {"type": "element_exists", "selector": "#search", "description": "Search input exists"},
            {"type": "element_count", "selector": "#fruit-list li", "expected": 7, "description": "Has 7 fruit items"},
            {"type": "input_event_test", "selector": "#search", "value": "app", "then_check": {"type": "visible_count", "selector": "#fruit-list li", "expected": 1}, "description": "Typing 'app' shows only 1 item (Apple)"},
            {"type": "input_event_test", "selector": "#search", "value": "", "then_check": {"type": "visible_count", "selector": "#fruit-list li", "expected": 7}, "description": "Clearing search shows all 7 items"},
        ]),
        "hints": json.dumps(["Listen to the 'input' event on the search box", "Use item.style.display = 'none' to hide and '' to show", "Use toLowerCase() for case-insensitive matching"]),
    },
    {
        "challenge_id": "character-counter",
        "title": "Live Character Counter",
        "category": "interactivity",
        "type": "dom_manipulation",
        "difficulty": "easy",
        "description": "Write JavaScript to show a live character count as the user types in the textarea.\n- Update the counter text to show 'X / 200' where X is the current character count\n- If the count exceeds 200, add the class 'over-limit' to the counter span",
        "starter_html": '<div class="counter-app">\n  <textarea id="message" placeholder="Type your message..."></textarea>\n  <span id="counter">0 / 200</span>\n</div>',
        "starter_css": "body { display:flex; justify-content:center; padding:2rem; font-family:sans-serif; }\n.counter-app { width:400px; }\n#message { width:100%; height:150px; padding:0.75rem; border:2px solid #ccc; border-radius:8px; font-size:1rem; resize:none; box-sizing:border-box; }\n#counter { display:block; text-align:right; margin-top:0.5rem; font-size:0.875rem; color:#666; }\n.over-limit { color:#ef4444 !important; font-weight:bold; }",
        "starter_js": "// Write your JavaScript here\n// Update the counter as the user types\n",
        "solution_html": '<div class="counter-app">\n  <textarea id="message" placeholder="Type your message..."></textarea>\n  <span id="counter">0 / 200</span>\n</div>',
        "solution_css": "body { display:flex; justify-content:center; padding:2rem; font-family:sans-serif; }\n.counter-app { width:400px; }\n#message { width:100%; height:150px; padding:0.75rem; border:2px solid #ccc; border-radius:8px; font-size:1rem; resize:none; box-sizing:border-box; }\n#counter { display:block; text-align:right; margin-top:0.5rem; font-size:0.875rem; color:#666; }\n.over-limit { color:#ef4444 !important; font-weight:bold; }",
        "solution_js": 'const textarea = document.getElementById("message");\nconst counter = document.getElementById("counter");\n\ntextarea.addEventListener("input", function() {\n  const len = textarea.value.length;\n  counter.textContent = len + " / 200";\n  if (len > 200) {\n    counter.classList.add("over-limit");\n  } else {\n    counter.classList.remove("over-limit");\n  }\n});',
        "test_cases": json.dumps([
            {"type": "element_exists", "selector": "#message", "description": "Textarea exists"},
            {"type": "element_exists", "selector": "#counter", "description": "Counter span exists"},
            {"type": "input_event_test", "selector": "#message", "value": "Hello", "then_check": {"type": "has_text", "selector": "#counter", "expected": "5 / 200"}, "description": "Typing 'Hello' shows '5 / 200'"},
        ]),
        "hints": json.dumps(["Listen to the 'input' event on the textarea", "Use textarea.value.length to get the character count", "Use classList.add/remove to toggle the 'over-limit' class"]),
    },
]
